Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'

  TargetRubyVersion: 2.5.1

Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'

